### ISSUE TITLE
Misleading infromation about utility version in the help message

### ISSUE THREAD

**Issue by SandakovMM** [plesk/dist-upgrader#2]
**STR**
1. Download the last version of ubuntu18to20 from [the release page](https://github.com/plesk/ubuntu18to20/releases/tag/v2.0.0)
2. Unpack and make it runnable
3. Call './ubuntu18to20 --help'

**Actual result:**
By now we have  following like "Utility version is v1.0.0." in the help message. I can see this is the version of the dist-upgrader framework, not the utility itself. Moreover there are another line about the utility version itself:
```
The currently selected upgrader is 'Plesk::Ubuntu18to20Upgrader' of version v2.0.0-1-g1857ba6.
```

**Proposal**
In my point of view the line looks misleading. It looks like it should be something like: "dist-upgrader framework version: ..." or "Plesk dist-upgrader ..." (just like in --version)

**Comment by kpushkaryov** [comment]
Fixed in #6.
