### ISSUE TITLE
Problem with looking for an upgrader on CentOS 7

### ISSUE THREAD

**Issue by SandakovMM** [plesk/dist-upgrader#4]
**Describe the bug**
Wrong system description on [looking for a upgrader on CentOS 7](https://github.com/plesk/dist-upgrader/blob/main/pleskdistup/main.py#L425).
It is happens because CentOS 7 [has following description: "CentOS Linux 7"](https://github.com/plesk/dist-upgrader/blob/main/pleskdistup/common/src/dist.py#L11). So when we split it by the first space "Linux 7" part moves to the os_from_version variable.
I propose to use the distro enum to recognize supported by a upgrader systems and which system do we use.

**Comment by kpushkaryov** [comment]
Fixed in #6.
